blank_issues_enabled: false
contact_links:
  - name: 💬 Questions & Discussion
    url: https://github.com/feifeixp/story-to-manga-enhanced/discussions
    about: Ask questions and discuss ideas with the community