name: ✨ Feature Request
description: Suggest a new feature or improvement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description
      description: What feature would you like to see added?
      placeholder: Describe the feature you'd like to request
    validations:
      required: true
  - type: textarea
    id: problem
    attributes:
      label: Problem it solves
      description: What problem does this feature solve?
      placeholder: Is your feature request related to a problem? Please describe.
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: How would you like this feature to work?
      placeholder: Describe the solution you'd like
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Are there alternative solutions you've considered?
      placeholder: Describe any alternative solutions you've considered
  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Add any other context about the feature request here